backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  # commit_messages:
  #   create: "Create {{collection}} “{{slug}}”"
  #   update: "Update {{collection}} “{{slug}}”"
  #   delete: "Delete {{collection}} “{{slug}}”"
  #   uploadMedia: "[skip ci] Upload “{{path}}”"
  #   deleteMedia: "[skip ci] Delete “{{path}}”"

# publish_mode: editorial_workflow

media_folder: public/images
public_folder: /images/uploads

collections:
  # site config and blog post meta info
  - name: "site_settings"
    label: "Site Settings"
    delete: false
    editor:
      preview: false
    files:
      - name: "navigation"
        label: "Navigation"
        file: "/content/navigation/navigation.json"
        fields:
          - label: "Navigation Groups"
            label_singular: "Navigation Group"
            name: "navigation_order"
            hint: "This sets the order of the Navigation Groups."
            widget: "list"
            fields:
              - label: "Navigation Group"
                name: "navigation_group"
                widget: "relation"
                collapsed: true
                collection: "navigation"
                search_fields:
                  - "name"
                display_fields:
                  - "name"
                value_field: "name"

      - name: "explore_avarice_navigation"
        label: "Explore Avarice Navigation"
        file: "/content/settings/explore-avarice-navigation.json"
        fields:
          - label: "World Overview"
            label_singular: "Page"
            name: "world_overview"
            widget: "list"
            fields:
              - label: "Page"
                name: "page"
                widget: "relation"
                collapsed: true
                collection: "explore_avarice"
                search_fields:
                  - "name"
                  - "slug"
                display_fields:
                  - "name"
                value_field: "{{name}} | {{slug}}"

          - label: "Races"
            label_singular: "Page"
            name: "races"
            widget: "list"
            fields:
              - label: "Page"
                name: "page"
                widget: "relation"
                collapsed: true
                collection: "explore_avarice"
                search_fields:
                  - "name"
                  - "slug"
                display_fields:
                  - "name"
                value_field: "{{name}} | {{slug}}"

          - label: "Organizations"
            label_singular: "Page"
            name: "organizations"
            widget: "list"
            fields:
              - label: "Page"
                name: "page"
                widget: "relation"
                collapsed: true
                collection: "explore_avarice"
                search_fields:
                  - "name"
                  - "slug"
                display_fields:
                  - "name"
                value_field: "{{name}} | {{slug}}"

          - label: "SURONIS"
            label_singular: "Page"
            name: "suronis"
            widget: "list"
            fields:
              - label: "Page"
                name: "page"
                widget: "relation"
                collapsed: true
                collection: "explore_avarice"
                search_fields:
                  - "name"
                  - "slug"
                display_fields:
                  - "name"
                value_field: "{{name}} | {{slug}}"

          - label: "World History"
            label_singular: "Page"
            name: "world_history"
            widget: "list"
            fields:
              - label: "Page"
                name: "page"
                widget: "relation"
                collapsed: true
                collection: "explore_avarice"
                search_fields:
                  - "name"
                  - "slug"
                display_fields:
                  - "name"
                value_field: "{{name}} | {{slug}}"

  - name: "navigation"
    label: "Navigation"
    label_singular: "Navigation Group"
    folder: "content/navigation"
    identifier_field: name
    create: true
    editor:
      preview: false
    fields:
      - label: "Name"
        name: "name"
        widget: "relation"
        collapsed: true
        collection: "pages"
        hint: "This will be the name of the group, and the page that it links to."
        options_length: 100
        search_fields:
          - "name"
        display_fields:
          - "name"
        value_field: "name"

      - label: "Pages"
        label_singular: "Page"
        name: "pages"
        widget: "list"
        fields:
          - label: "Page"
            name: "page"
            widget: "relation"
            collapsed: true
            collection: "pages"
            options_length: 100
            search_fields:
              - "name"
            display_fields:
              - "name"
            value_field: "name"

  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "content/pages"
    identifier_field: name
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD",
          dateFormat: "YYYY-MM-DD",
          timeFormat: false,
        }
      - label: "SEO Data"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Hero Banner", name: "hero_banner", widget: "image", required: false }
      - { label: "Page Headline", name: "page_headline", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }

      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false

      - label: Author
        name: "author"
        widget: relation
        collection: "meta"
        file: "authors"
        searchFields:
          - "authors.*.name"
        displayFields:
          - "authors.*.name"
        valueField: "authors.*.slug"

      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"

      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "explore_avarice"
    label: "Explore Avarice"
    label_singular: "Page"
    folder: "content/pages/explore"
    identifier_field: name
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "SEO Data"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Hero Banner", name: "hero_banner", widget: "image", required: false }
      - { label: "Page Headline", name: "page_headline", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "races"
    label: "Races"
    folder: "content/races"
    create: true
    fields:
      - { label: "name", name: "name", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "race history"
    label: "Race History"
    folder: "content/playable-races"
    create: true
    fields:
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "corponations"
    label: "CorpoNations"
    folder: "content/corponations"
    create: true
    fields:
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "corponations history"
    label: "CorpoNations History"
    folder: "content/playable-races"
    create: true
    fields:
      - { label: "Body", name: "body", widget: "markdown" }

  # site config and blog post meta info
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "navigation"
        label: "Navigation"
        file: "navigation-config.json"
        fields:
          - label: "Main Navigation"
            name: "navigation"
            widget: "list"
            hint: "hello there"
            fields:
              - label: "Page"
                name: "page"
                widget: "relation"
                collection: "races"
                #file: "authors"
                search_fields:
                  - "name"
                display_fields:
                  - "name"
                value_field: "name"

      - name: "sec-navigation"
        label: "Secondary Navigation"
        file: "sec-navigation-config.json"
        fields:
          - label: "Main Navigation"
            name: "navigation"
            widget: "list"
            hint: "hello there"
            fields:
              - label: "Page"
                name: "page"
                widget: "relation"
                collection: "pages"
                #file: "authors"
                search_fields:
                  - "name"
                display_fields:
                  - "name"
                value_field: "name"

      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "authors"
        label: "Authors"
        file: "meta/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            label_singular: "Author"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the author"
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "First and Last"
              - label: "Introduction"
                name: "introduction"
                widget: "text"
      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"
